// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETDEFINE_H_
#define FLATBUFFERS_GENERATED_PACKETDEFINE_H_

#include "flatbuffers/flatbuffers.h"

struct Vec3;

struct Message;
struct MessageBuilder;

struct C2S_HEARTBEAT;
struct C2S_HEARTBEATBuilder;

struct S2C_HEARTBEAT;
struct S2C_HEARTBEATBuilder;

enum MESSAGE_ID : uint8_t {
  MESSAGE_ID_NONE = 0,
  MESSAGE_ID_C2S_HEARTBEAT = 1,
  MESSAGE_ID_S2C_HEARTBEAT = 2,
  MESSAGE_ID_MIN = MESSAGE_ID_NONE,
  MESSAGE_ID_MAX = MESSAGE_ID_S2C_HEARTBEAT
};

inline const MESSAGE_ID (&EnumValuesMESSAGE_ID())[3] {
  static const MESSAGE_ID values[] = {
    MESSAGE_ID_NONE,
    MESSAGE_ID_C2S_HEARTBEAT,
    MESSAGE_ID_S2C_HEARTBEAT
  };
  return values;
}

inline const char * const *EnumNamesMESSAGE_ID() {
  static const char * const names[4] = {
    "NONE",
    "C2S_HEARTBEAT",
    "S2C_HEARTBEAT",
    nullptr
  };
  return names;
}

inline const char *EnumNameMESSAGE_ID(MESSAGE_ID e) {
  if (flatbuffers::IsOutRange(e, MESSAGE_ID_NONE, MESSAGE_ID_S2C_HEARTBEAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMESSAGE_ID()[index];
}

template<typename T> struct MESSAGE_IDTraits {
  static const MESSAGE_ID enum_value = MESSAGE_ID_NONE;
};

template<> struct MESSAGE_IDTraits<C2S_HEARTBEAT> {
  static const MESSAGE_ID enum_value = MESSAGE_ID_C2S_HEARTBEAT;
};

template<> struct MESSAGE_IDTraits<S2C_HEARTBEAT> {
  static const MESSAGE_ID enum_value = MESSAGE_ID_S2C_HEARTBEAT;
};

bool VerifyMESSAGE_ID(flatbuffers::Verifier &verifier, const void *obj, MESSAGE_ID type);
bool VerifyMESSAGE_IDVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKET_TYPE = 4,
    VT_PACKET = 6
  };
  MESSAGE_ID packet_type() const {
    return static_cast<MESSAGE_ID>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const C2S_HEARTBEAT *packet_as_C2S_HEARTBEAT() const {
    return packet_type() == MESSAGE_ID_C2S_HEARTBEAT ? static_cast<const C2S_HEARTBEAT *>(packet()) : nullptr;
  }
  const S2C_HEARTBEAT *packet_as_S2C_HEARTBEAT() const {
    return packet_type() == MESSAGE_ID_S2C_HEARTBEAT ? static_cast<const S2C_HEARTBEAT *>(packet()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifyMESSAGE_ID(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
};

template<> inline const C2S_HEARTBEAT *Message::packet_as<C2S_HEARTBEAT>() const {
  return packet_as_C2S_HEARTBEAT();
}

template<> inline const S2C_HEARTBEAT *Message::packet_as<S2C_HEARTBEAT>() const {
  return packet_as_S2C_HEARTBEAT();
}

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_packet_type(MESSAGE_ID packet_type) {
    fbb_.AddElement<uint8_t>(Message::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(Message::VT_PACKET, packet);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    MESSAGE_ID packet_type = MESSAGE_ID_NONE,
    flatbuffers::Offset<void> packet = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

struct C2S_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef C2S_HEARTBEATBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DUMMY = 6
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const flatbuffers::String *dummy() const {
    return GetPointer<const flatbuffers::String *>(VT_DUMMY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_DUMMY) &&
           verifier.VerifyString(dummy()) &&
           verifier.EndTable();
  }
};

struct C2S_HEARTBEATBuilder {
  typedef C2S_HEARTBEAT Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(C2S_HEARTBEAT::VT_ID, id, 0);
  }
  void add_dummy(flatbuffers::Offset<flatbuffers::String> dummy) {
    fbb_.AddOffset(C2S_HEARTBEAT::VT_DUMMY, dummy);
  }
  explicit C2S_HEARTBEATBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<C2S_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<C2S_HEARTBEAT>(end);
    return o;
  }
};

inline flatbuffers::Offset<C2S_HEARTBEAT> CreateC2S_HEARTBEAT(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> dummy = 0) {
  C2S_HEARTBEATBuilder builder_(_fbb);
  builder_.add_dummy(dummy);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<C2S_HEARTBEAT> CreateC2S_HEARTBEATDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *dummy = nullptr) {
  auto dummy__ = dummy ? _fbb.CreateString(dummy) : 0;
  return CreateC2S_HEARTBEAT(
      _fbb,
      id,
      dummy__);
}

struct S2C_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef S2C_HEARTBEATBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DUMMY = 6
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const flatbuffers::String *dummy() const {
    return GetPointer<const flatbuffers::String *>(VT_DUMMY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_DUMMY) &&
           verifier.VerifyString(dummy()) &&
           verifier.EndTable();
  }
};

struct S2C_HEARTBEATBuilder {
  typedef S2C_HEARTBEAT Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(S2C_HEARTBEAT::VT_ID, id, 0);
  }
  void add_dummy(flatbuffers::Offset<flatbuffers::String> dummy) {
    fbb_.AddOffset(S2C_HEARTBEAT::VT_DUMMY, dummy);
  }
  explicit S2C_HEARTBEATBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<S2C_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<S2C_HEARTBEAT>(end);
    return o;
  }
};

inline flatbuffers::Offset<S2C_HEARTBEAT> CreateS2C_HEARTBEAT(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> dummy = 0) {
  S2C_HEARTBEATBuilder builder_(_fbb);
  builder_.add_dummy(dummy);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<S2C_HEARTBEAT> CreateS2C_HEARTBEATDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *dummy = nullptr) {
  auto dummy__ = dummy ? _fbb.CreateString(dummy) : 0;
  return CreateS2C_HEARTBEAT(
      _fbb,
      id,
      dummy__);
}

inline bool VerifyMESSAGE_ID(flatbuffers::Verifier &verifier, const void *obj, MESSAGE_ID type) {
  switch (type) {
    case MESSAGE_ID_NONE: {
      return true;
    }
    case MESSAGE_ID_C2S_HEARTBEAT: {
      auto ptr = reinterpret_cast<const C2S_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MESSAGE_ID_S2C_HEARTBEAT: {
      auto ptr = reinterpret_cast<const S2C_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMESSAGE_IDVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMESSAGE_ID(
        verifier,  values->Get(i), types->GetEnum<MESSAGE_ID>(i))) {
      return false;
    }
  }
  return true;
}

inline const Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<Message>(buf);
}

inline const Message *GetSizePrefixedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Message>(buf);
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Message>(nullptr);
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Message> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PACKETDEFINE_H_
